services:
  sas_force_sensor_bota_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TIMEOUT=20
      - DISPLAY
      - ROS_DOMAIN_ID
    privileged: true # Needed for USB connection
    volumes:
      - ~/.Xauthority:/root/.Xauthority # x server related
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # x server related
    command: /bin/bash -c "
      cd /root/sas_force_sensor_bota_devel
      && colcon build
      && source install/setup.bash
      && timeout -s INT $$TIMEOUT ros2 launch sas_force_sensor_bota sas_force_sensor_bota_launch.py"

  sas_force_sensor_bota_client:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TIMEOUT=20
      - ROS_DOMAIN_ID
    command: /bin/bash -c "
      cd /root/sas_force_sensor_bota_devel
      && colcon build
      && source install/setup.bash
      && timeout -s INT $$TIMEOUT ros2 run sas_force_sensor_bota sas_force_sensor_client_example_node"
